from supabase import create_client

SUPABASE_URL = "https://ncwgczobyjbjggkmyveg.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jd2djem9ieWpiamdna215dmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjA4NzIsImV4cCI6MjA5MDAzNjg3Mn0.AIvYOwFQBoXYIN5kfY9Du_V8ny3f_CnMWvjO_-qJciY"

supabase = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
